# Generated by Django 4.2.7 on 2023-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct',
            field=models.BooleanField(default=True, verbose_name='정답여부'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='prompt',
            field=models.TextField(verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='response',
            field=models.TextField(verbose_name='답변'),
        ),
    ]
